spring:
  application:
    name: hackathon

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://psql:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update # You can set to create-drop, update, create, or validate
      show-sql: true # Set to true to show SQL queries in console
      database-platform: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  dialect=org:
    hibernate:
      dialect:
  level:
    root: debug

